title: My Awesome Site
email: ''
description: ''
baseurl: /
author:
  name: ''
  twitter: ''
  picture: ''
twitter_username: ''
github_username: ''
logo: ''
search: true
paginate: 10
paginate_path: '/page:num/'
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      read_time: true
lang: en-US
url: ''
search_full_content: false
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: true
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs
  - /example
